package objenome;

/**
 * The context generated by an individual Objosome
 */
public class ObjosomeContext extends DefaultContext {
    private final Objosome objosome;
    private final GeneContext parent;

    public ObjosomeContext(Objosome o) {
        super(o.parentContext);
        this.objosome = o;
        this.parent = o.parentContext;
        
        for (Objene g : o) {
            g.apply(this);
        }
    }
    
    
}
