package objenome;

/**
 * The container (phenotype) generated by an individual Objosome
 */
public class Phenotainer extends Container {
    private final Objosome objosome;
    private final Genetainer parent;

    public Phenotainer(Objosome o) {
        super(o.parentContext);
        this.objosome = o;
        this.parent = o.parentContext;
        
        for (Objene g : o) {
            g.apply(this);
        }
    }
    
    
}
