package objenome;

import java.lang.reflect.Parameter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The container (phenotype) generated by an individual Objenome
 */
public class Phenotainer extends Container {
    public final Map<Parameter, Object> parameterValues = new HashMap();
    public final Objenome objosome;
    public final Genetainer parent;

    public Phenotainer(Objenome o) {
        super(o.parentContext);        
        this.objosome = o;
        this.parent = o.parentContext;
        
        
        
        //remove all builders with ambiguosity
        List<String> toRemove = new ArrayList();
        for (Map.Entry<String, Builder> e : this.builders.entrySet()) {
            if (e.getValue() instanceof Parameterized)
                toRemove.add(e.getKey());
        }
        for (String s : toRemove) this.builders.remove(s);
        
        
        
        for (Objene g : o.getGenes()) {
            g.apply(this);
        }
    }
    
    public void use(Parameter p, Object value) {
        parameterValues.put(p, value);
    }

    public <T> T get(Parameter p) {
        return (T) parameterValues.get(p);
    }
    
}
